# Generated by Django 3.1.4 on 2021-01-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_auto_20201113_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='input_type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('multiselect', 'Multi Select'), ('file', 'File'), ('boolean', 'Boolean')], default='dropdown', max_length=50),
        ),
    ]
